wandb_key: 69c26cd17e0bb8b19fa95f247367679de9a43ed9
clip_download_dir: /home/yliu/projects/DataDream-ECCV2024-private/classify/CLIP
metadata_dir: metadata/tinyimagenet

data_dir: /shared-network/yliu/projects/disef/fine-tune/data/

real_train_data_dir:
    tinyimagenet: /shared-network/yliu/projects/disef/fine-tune/data/tinyimagenet

real_train_fewshot_data_dir: /shared-network/yliu/projects/disef/fine-tune/selected_fewshots/tinyimagenet/seed_5

synth_train_data_dir: /shared-network/yliu/projects/disef/generation/output/tinyimagenet-realistic-step5/seed_5

# generative_model:
#             sd2.1: /home/yliu/projects/diffuser/stable-diffusion-2-1-base
