wandb_key: b52e9ac2a70a48f9091d5b7387be4a897f218ef7
clip_download_dir: /shared-local/jkim32/clip
metadata_dir: metadata/imagenet

data_dir: /shared-local/jkim32/data

real_train_data_dir:
    eurosat: /shared-local/jbader40/data/eurosat/EuroSAT

real_train_fewshot_data_dir: /shared-local/jkim32/data/{}/real_train_fewshot

synth_train_data_dir: /shared-local/jkim32/data

generative_model:
            sd2.1: /shared-local/jkim32/huggingface/diffusers/models--stabilityai--stable-diffusion-2-1-base/snapshots/1f758383196d38df1dfe523ddb1030f2bfab7741
